### PR TITLE
Oauth2

### PR DESCRIPTION
**Pull request by mtdowling**
Creating a PR for #20 that houses the oauth2 repo on the main Guzzle repo.

### CODE REVIEW

**Comment by billmn** [comment]
Any news about this?

**Comment by ramsey** [comment]
I would recommend Option 2. This would open the possibility for others to inject different OAuth 2 adapters, if they don't want to use the one provided by the League. It also means you're not locked into our 0.x or 1.x API. Since our API will be changing from now until the 1.0.0 release, you'll be able to upgrade easier by changing the internals of your adapter.

**Comment by pjcdawkins** [comment]
We have this:
https://github.com/commerceguys/guzzle-oauth2-plugin

It's a port of our existing plugin from Guzzle 3 to 5. It's significantly smaller than this effort (and it needs tests). Feel free to take what you need of course.

**Comment by HipsterJazzbo** [comment]
Ping. What's the thnking on this now? The current version of [league/oauth2-client](https://github.com/thephpleague/oauth2-client) uses Guzzle 6, so that's not an issue anymore. I'm gonna need this for several projects, so I thought I'd check in here before I write a whole thing. Maybe I could contribute something?

**Comment by isleshocky77** [comment]
Has there been any updates or changes to this PR or the thinking behind how to use Oauth2 with Guzzle 6?  Have most people started just using thephpleague/oauth2-client entirely?

**Comment by kamermans** [comment]
I'm still using the `oauth2` branch in many of my production projects.  If we use phpleague for OAuth2, why not use them also for OAuth1 and just make this project a compatibility wrapper for Guzzle <=> phpleague?

**Comment by sagikazarmark** [comment]
@kamermans I like the idea, there is one problem though: they are locked to Guzzle 6, which means if Guzzle 7 comes out with BC breaks, this subscriber won't work with it, since the Oauth 2 package won't support Guzzle 7.

**Comment by mathroc** [comment]
fwiw, https://github.com/sainsburys/guzzle-oauth2-plugin is working well with Guzzle 6

**Comment by GrahamCampbell** [comment]
Stale.

**Comment by cweiske** [comment]
Also see #1.

**Pull request closed without merging**
