### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**
// cc @guzzle/maintainers

### CODE REVIEW

**Comment by Nyholm** [comment]
Travis is super red.

**Comment by GrahamCampbell** [comment]
I blame Travis for being impossibly slow. It looks like it was caused by merging a PR which was green, but only because it was out of date, and then Travis took hours to run after merge. :/

**Comment by GrahamCampbell** [comment]
Fixed. :shipit:

**Comment by pb-sobrien** [comment]
@guzzle/maintainers sorry for the bump. Any chance this could be reviewed? :)

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
