### PR TITLE
Added require ext-openssl

### PR DESCRIPTION
**Pull request by thecaliskan**

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
👎 here in the strongest possible terms. This cannot happen on anything other than a major release. Instead, it should be added as a suggest.

**Comment by thecaliskan** [comment]
Bull sh

**Comment by GrahamCampbell** [comment]
Do you not see that this PR does not fix that? If someone doesn't have openssl, composer will just install an older version of this package...

**Comment by GrahamCampbell** [comment]
It is for this reason that you must only add this to suggest for now, then move to require when we come to do the next major release.

**Pull request closed without merging**
